version: '3'

services:
  schema-registry:
    build: schema-registry-service
    container_name: schema-registry
    ports:
      - "3000:80"

  billing:
    build: ./billing-service
    container_name: billing
    ports:
      - "3003:3003"
    depends_on:
      - broker
      - postgres
      - schema-registry
      - auth
    environment:
      PORT: 3003
      DB_NAME: billing
      DB_HOST: postgres
      KAFKA_BROKER: broker:9092
      KAFKA_GROUP: uber-popug-billing
      AUTH_SERVICE_HOSTNAME: auth:3001
      SCHEMA_SERVICE_HOSTNAME: schema-registry:80

  auth:
    build: ./auth-service
    container_name: auth
    ports:
      - "3001:3001"
    depends_on:
      - broker
      - postgres
      - schema-registry
    environment:
      PORT: 3001
      DB_NAME: auth
      DB_HOST: postgres
      KAFKA_BROKER: broker:9092
      SALT: cafebabe
      TOKEN_SIGN_KEY: baadfood
      SCHEMA_SERVICE_HOSTNAME: schema-registry:80

  tracker:
    build: ./tracker-service
    container_name: tracker
    ports:
      - "3002:3002"
    depends_on:
      - broker
      - postgres
      - auth
      - schema-registry
    environment:
      PORT: 3002
      DB_NAME: tracker
      DB_HOST: postgres
      KAFKA_BROKER: broker:9092
      KAFKA_GROUP: uber-popug-tracker
      AUTH_SERVICE_HOSTNAME: auth:3001
      SCHEMA_SERVICE_HOSTNAME: schema-registry:80

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    platform: linux/arm64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    platform: linux/arm64
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

